### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by cppshizoidS** [jake-stewart/jfind#12]
/home/cppshizoid/jfind/src/item_exact_matcher.cpp: In member function ‘virtual bool ItemExactMatcher::setQuery(std::string)’:
/home/cppshizoid/jfind/src/item_exact_matcher.cpp:36:24: error: no matches converting function ‘strcasestr’ to type ‘char* (*)(const char*, const char*)’
   36 |         m_comparison = strcasestr;
      |                        ^~~~~~~~~~
In file included from /usr/include/c++/13.1.1/cstring:42,
                 from /home/cppshizoid/jfind/src/item_exact_matcher.cpp:7:
/usr/include/string.h:376:26: note: candidates are: ‘const char* strcasestr(const char*, const char*)’
  376 | extern "C++" const char *strcasestr (const char *__haystack,
      |                          ^~~~~~~~~~
/usr/include/string.h:374:20: note:                 ‘char* strcasestr(char*, const char*)’
  374 | extern "C++" char *strcasestr (char *__haystack, const char *__needle)
      |                    ^~~~~~~~~~
/home/cppshizoid/jfind/src/item_exact_matcher.cpp:39:24: error: no matches converting function ‘strstr’ to type ‘char* (*)(const char*, const char*)’
   39 |         m_comparison = strstr;
      |                        ^~~~~~
/usr/include/string.h:343:1: note: candidates are: ‘const char* strstr(const char*, const char*)’
  343 | strstr (const char *__haystack, const char *__needle) __THROW
      | ^~~~~~
/usr/include/string.h:337:1: note:                 ‘char* strstr(char*, const char*)’
  337 | strstr (char *__haystack, const char *__needle) __THROW
      | ^~~~~~
[ 29%] Building CXX object CMakeFiles/jfind.dir/src/key.cpp.o
make[2]: *** [CMakeFiles/jfind.dir/build.make:230: CMakeFiles/jfind.dir/src/item_exact_matcher.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/jfind.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by jake-stewart** [comment]
it should be fixed with latest commit.
